# Adam Keys' Rails app template
# =============================
#
# Generate an application, just like Adam Keys likes them.

# Testing dependencies
# ------------

gem_group :development, :test do
  gem 'rspec-rails'
end
run "rm -rf test" # Is there a way to set the -T option on the new command?

# Development dependencies
# ------------

gem_group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'meta_request'
  gem 'foreman'
end

# Application dependencies
# ------------------------
gem 'resque'
gem 'unicorn'
gem 'yajl-ruby'
gem 'warden-github-rails'

# Front-end dependencies
# ----------------------

# Baseline configuration
# ----------------------

# (basic routes, use ENV for configuration values, etc.)

# Vendor front-end bits
# ---------------------

# Fiddly things
# -------------

run "rm README.rdoc"
run %Q{echo "# An awesome new app!" > README.md}

# Bootstrapping
# -------------

run "bundle install"
generate 'rspec:install'

# setup DB
git :init
git add: "."
git commit: %Q{ -m 'Generated by github_addon.rb' }

# TODO the default app generator runs bundle after this, killing all the lovely
# commentary from the last two commands, fix that!

